### PR TITLE
Minor tweaks for GitHub users

### PR DESCRIPTION
**Pull request by hoosierEE**
Unfortunately this PR has a bunch of debris related to #10, I'll do more feature branches in the future.

### CODE REVIEW

**Comment by iocane** [comment]
Hi, Alex, I updated the macosx script in the latest commit 58e6e07a7c42de430dc238b28f9d186fbeaabe9c in the release branch. The one you committed was behind on some changes. Can you try doing a clean checkout of that and building with the default tup.config.

**Comment by hoosierEE** [comment]
Nice, `tup` builds without errors (`release` branch, OSX).

**Comment by iocane** [comment]
Can turn the tests on now and try it out?

**Comment by hoosierEE** [comment]
I pulled a fresh copy of unbox and checked out the release branch.  It builds, but has a failing test:

```
$ tup
[ tup ] [0.000s] Scanning filesystem...
[ tup ] [0.006s] Reading in new environment variables...
[ tup ] [0.006s] No Tupfiles to parse.
[ tup ] [0.006s] No files to delete.
[ tup ] [0.006s] Executing Commands...
 [ ]   0%tup error: FUSE did not appear to release all file descriptors after the sub-process closed.
 *** Command ID=2648 failed: bin/jconsole -test test/stack build/test gstack.ijs
 [ ]   0%                                                                                                              
 *** tup: 1 job failed.
```

I'll close this PR for now.

**Pull request closed without merging**
